[package]
name = "kinderdom"
version = "0.1.0"
authors = ["denis <orca84@protonmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.3", features = ["postgres"] }
rocket= "0.4.2"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["diesel_postgres_pool", "tera_templates", "serve"]
